// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_test_key_for_web_development',
    appId: '1:123456789012:web:abcdef123456789',
    messagingSenderId: '123456789012',
    projectId: 'ran-san-maker-test',
    authDomain: 'ran-san-maker-test.firebaseapp.com',
    storageBucket: 'ran-san-maker-test.appspot.com',
    measurementId: 'G-ABCDEF1234',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_test_key_for_android_development',
    appId: '1:123456789012:android:abcdef123456789',
    messagingSenderId: '123456789012',
    projectId: 'ran-san-maker-test',
    storageBucket: 'ran-san-maker-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_test_key_for_ios_development',
    appId: '1:123456789012:ios:abcdef123456789',
    messagingSenderId: '123456789012',
    projectId: 'ran-san-maker-test',
    storageBucket: 'ran-san-maker-test.appspot.com',
    iosBundleId: 'com.example.ranSanMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_test_key_for_macos_development',
    appId: '1:123456789012:macos:abcdef123456789',
    messagingSenderId: '123456789012',
    projectId: 'ran-san-maker-test',
    storageBucket: 'ran-san-maker-test.appspot.com',
    iosBundleId: 'com.example.ranSanMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_test_key_for_windows_development',
    appId: '1:123456789012:windows:abcdef123456789',
    messagingSenderId: '123456789012',
    projectId: 'ran-san-maker-test',
    storageBucket: 'ran-san-maker-test.appspot.com',
  );
}